name: Step 7, Create release v1.0.1

# This step triggers after 6-commit-hotfix.yml.
# This workflow updates from step 7 to step X.

# This will run when a release is published.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  release:
    types: [published]

# Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  contents: write

jobs:
  

  on_hotfix_release_published:
    name: On hotfix release v1.0.1 published
    

    # We'll run Ubuntu for performance instead of Mac or Windows.
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Update README from step 7 to step X.
      - name: Update to finish
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 7
          to_step: X
